### ISSUE TITLE
프로젝트 채팅방 소켓io 구현

### ISSUE THREAD

**Issue by WON-JIN-LEE** [teaming-project-team3/teaming_backend#16]
## Description
프로젝트룸에서 채팅으로 실시간 소통이 가능함
room과 해당 room에 참가한 사용자 데이터를 몽고DB에 저장해서 데이터를 불러올 수 있도록 구현

## Todo
- [x] chat 스키마 구현
- [x] socket.io 라이브러리를 이용한 소켓 서버 구현
- [x] 클라이언트 소켓 서버 접속, disconnecting 일 때 현재 room에 참가된 사용자 data 전달
- [x] 접속된 사용자가 하나의 방에 중첩되는 문제
